config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'pages/favorites'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :locations
  resources :cocktails, only: [:index, :show, :new, :create]
  resources :cocktails do
    resources :doses, only: [:new, :create, :destroy]

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: :true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail }

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: :true

end

app/models/location.rb
class Location < ApplicationRecord
  attr_accessor :adress, :latitude ,:longitude
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.create(cocktail_params)
    redirect_to(new_cocktail_dose_path(@cocktail.id))
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
   @cocktail = Cocktail.find(params[:cocktail_id])
   @dose = Dose.new
  end

 def create
   @cocktail = Cocktail.find(params[:cocktail_id])
   @dose = Dose.new(dose_params)
   @dose.cocktail = @cocktail
   if @dose.save
     redirect_to(cocktail_path(@cocktail))
   else
     render :new
   end
 end

 def destroy
  @cocktail = Cocktail.find(params[:cocktail_id])
  @dose = Dose.find(params[:id])
  @dose.destroy
  redirect_to(cocktail_path(@cocktail))
 end

 private

 def dose_params
   params.require(:dose).permit(:description, :ingredient_id)
 end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    if params[:search].present?
      @locations = Location.near(params[:search], 50, :order => :distance)
    else
      @locations = Location.all
    end
  end

  def show
    @location = Location.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/index.html.erb
<div class="front">
  <div class="index_image" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1511318042200-2bf4c8f20ca5?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1600&h=900&fit=crop&s=1c8f9be9d6ea152a7eb864a63bb394b0');">
    <div class="index_title">
      <a href="#scroll"><i class="fas fa-angle-double-down"></i></a>
    </div>
  </div>
</div>


<div class="container">
  <h2 class="text-center">These are all the Cocktails:</h2>
  <p class="text-center color"><%= link_to 'ADD YOUR OWN COCKTAIL', new_cocktail_path %></p>
  <br>
  <div class="cards">
    <div id="adding" class="card">
      <%= link_to pages_favorites_path do %>
      <i class="fas fa-heart good"></i>
      <h3 class="fav_title">Our Favorites</h3>
      <% end %>
    </div>
    <% @cocktails.each do |cocktail| %>
    <%= link_to cocktail_path(cocktail) do %>
    <div class="card">
      <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path cocktail.photo, height: 300, width: 400, crop: :fill %>')">
        <span class="card-category"><%= cocktail.name %></span>
        <div class="card-description">
        <span><%= cocktail.description %></span>
        </div>
      </div>
      <div class="card-footer">
        <p>More Information</p>
        <div class="controls">
          <a href="#"><i class="fa fa-star"></i></a>
          <a href="#"><i class="fa fa-heart"></i></a>
          <a href="#"><i class="fa fa-share"></i></a>
          <%= link_to cocktail_path(cocktail), method: :delete do %><i class="far fa-trash-alt"></i><% end %>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>
    <div id="adding" class="card">
      <%= link_to new_cocktail_path do %>
      <i class="fas fa-plus"></i>
      <% end %>
    </div>
  </div>
</div>
<div id="scroll"></div>
<!-- <a href="#scroll"></a> -->

app/views/cocktails/new.html.erb
<h1>Create a cocktail</h1>
<div class="label">
  <%= simple_form_for [@cocktail] do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit "Add a cocktail", class: "btn btn-primary" %>
  <% end %>
</div>
<%= link_to "Back", cocktails_path, class: "btn btn-primary" %>

app/views/cocktails/show.html.erb
<div class="label"></div>
  <h1> <%= @cocktail.name %> </h1>
  <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>
  <h3> <%= @cocktail.description %> </h3>
  <ul> <% @cocktail.doses.each do |dose| %>
    <li class="color"> <%= dose.ingredient.name %>  -  <%= dose.description %>   ||   <%= link_to cocktail_dose_path(@cocktail,dose), method: :delete do %><i class="far fa-trash-alt"></i><% end %> </li>
    <% end %>
  </ul>
</div>

<%= link_to "Add ingredients", new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %>
<%= link_to "Back", cocktails_path, class: "btn btn-primary" %>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<h1>Add an ingredient</h1>
<div class="label">
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.association :ingredient %>
    <%= f.input :description %>
    <%= f.submit "Add an ingredient", class: "btn btn-primary" %>
  <% end %>
</div>
<%= link_to "Back", cocktail_path(@cocktail), class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/locations/index.html.erb
<%= form_tag locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>

<table>
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
  </tr>
  <% for location in @locations %>
  <tr>
    <td>location.address</td>
    <td>location.latitude</td>
    <td>location.longitude</td>
    <td><%= link_to "Show", location %></td>
  </tr>
  <% end %>
</table>


















<% my_url = "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=15" %>
<% @locations.each do |location| %>
<% my_url += "&markers=#{location.latitude}%2C#{location.longitude}" %>
<% end %>
<%= image_tag my_url %>

app/views/locations/show.html.erb
<p>
  <strong>Address:</strong>
  <%= @location.address  %>
</p>
<p>
  <strong>Latitude:</strong>
  <%= @location.latitude  %>
</p>
<p>
  <strong>Longitude:</strong>
  <%= @location.longitude  %>
</p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>

<h3>Nearby Locations:</h3>
<ul>
  <% for location in @location.nearbys(10) %>
  <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
  <% end %>
</ul>


<p>
  <%= link_to "View All", locations_path  %>
</p>









<h3>Nearby locations</h3>
<ul>
<% for location in @location.nearbys(10) %>
  <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
<% end %>
</ul>

app/views/pages/favorites.html.erb
<div class="back">
  <div id="cook"></div>
  <div class="index-block" id="ToC">
    <h2 class="index-title">The Spirits:</h2>
    <br>
    <div class="alles">
      <div class="champ">
        <img src="https://www.shareicon.net/data/128x128/2016/03/24/738612_party_512x512.png">
      </div>
      <div class="tab1">
        <table class="table_alignment">
          <tbody>
            <tr>
              <td class="hip">
                <ul class="list-inline">
                  <li><a href="#gin">Gin Drinks</a></li>
                  <li><a href="#whiskey">Whiskey Drinks</a></li>
                  <li><a href="#tequila">Tequila Drinks</a></li>
                  <li><a href="#rum">Rum and Cachaça</a></li>
                </ul>
              </td>
              <td class="pads">
                <ul class="list-inline">
                  <li><a href="#vodka">Vodka Drinks</a></li>
                  <li><a href="#brandy">Brandy Drinks</a></li>
                  <li><a href="#aperitifs">Aperitifs</a></li>
                  <li><a href="#Amari">Amari, and More</a></li>
                </ul>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="kein_champ">
        <img src="https://www.shareicon.net/data/128x128/2016/03/24/738622_people_512x512.png">
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <a href="#scroll"><i class="fas fa-angle-double-down" style="color: #494C50"></i></a>
  <br>
  <br>
  <br>
  <div class="field">
    <div id="scroll"></div>
    <h3>Sazerac</h3>
    <p class="cubic">This is whiskey, bitters, and sugar, in an absinthe-coated glass</p>
    <img class="img_fav" src="http://static1.businessinsider.de/image/57f4e8a5dd08954e358b48ce-1200/10-sazerac-this-is-whiskey-bitters-and-sugar-in-an-absinthe-coated-glass.jpg">
    <br>
    <br>
    <br>
    <br>
    <h3>Mojito</h3>
    <p class="cubic">The Cuban classic was among the top 10 in more than a third of the bars polled. It's made with rum, lime juice, soda, brown cane sugar, fresh mint, and ice.</p>
    <img class="img_fav" src="http://static4.businessinsider.de/image/57f4e8a3dd08954e358b48cc-1200/9-mojito-the-cuban-classic-was-among-the-top-10-in-more-than-a-third-of-the-bars-polled-its-made-with-rum-lime-juice-soda-brown-cane-sugar-fresh-mint-and-ice.jpg">
    <br>
    <br>
    <br>
    <br>
    <h3>Moscow Mule</h3>
    <p class="cubic">This is vodka's answer to the Dark 'N' Stormy, according to Drinks International. It's served in a copper mug filled with vodka, lime, ginger, and soda.</p>
    <img class="img_fav" src="http://static2.businessinsider.de/image/57f4e8a4dd08954e358b48cd-1200/8-moscow-mule-this-is-vodkas-answer-to-the-dark-n-stormy-according-to-drinks-international-its-served-in-a-copper-mug-filled-with-vodka-lime-ginger-and-soda.jpg">
    <br>
    <br>
    <br>
    <br>
    <h3>Margarita</h3>
    <p class="cubic">The frozen favourite has stayed in seventh place, though at 40% of the bars polled the drink isn't served frozen. It's best made with tequila, fresh lime juice, and agave syrup.</p>
    <img class="img_fav" src="http://static4.businessinsider.de/image/57f4e8a5dd08954e358b48cf-1200/7-margarita-the-frozen-favourite-has-stayed-in-seventh-place-though-at-40-of-the-bars-polled-the-drink-isnt-served-frozen-its-best-made-with-tequila-fresh-lime-juice-and-agave-syrup.jpg">
    <br>
    <br>
    <br>
    <br>
    <h3>Dry Martini</h3>
    <p class="cubic">This chic classic is made with gin and vermouth, garnished with an olive or a lemon twist.</p>
    <img class="img_fav" src="http://static4.businessinsider.de/image/57f4e8a6dd08954e358b48d1-1200/6-dry-martini-this-chic-classic-is-made-with-gin-and-vermouth-garnished-with-an-olive-or-a-lemon-twist.jpg">
    <br>
    <br>
    <br>
    <br>
    <h3>Whiskey Sour</h3>
    <p class="cubic">The dependable cocktail is made with bourbon, lemon juice, and a teaspoon of sugar.</p>
    <img class="img_fav" src="http://static3.businessinsider.de/image/57f4e8a6dd08954e358b48d0-1200/5-whiskey-sour-the-dependable-cocktail-is-made-with-bourbon-lemon-juice-and-a-teaspoon-of-sugar.jpg">
    <br>
    <br>
    <br>
    <br>
    <h3>Manhattan</h3>
    <p class="cubic">Down from its third place spot last year, this was a top seller in more than half of the bars polled, most frequently made with peppery rye, bitters, and sweet vermouth with Bulleit, Rittenhouse, and Maker's Mark.</p>
    <img class="img_fav" src="http://static1.businessinsider.de/image/57f4e8a7dd08954e358b48d3-1200/4-manhattan-down-from-its-third-place-spot-last-year-this-was-a-top-seller-in-more-than-half-of-the-bars-polled-most-frequently-made-with-peppery-rye-bitters-and-sweet-vermouth-with-bulleit-rittenhouse-and-makers-mark.jpg">
    <br>
    <br>
    <br>
    <br>
    <h3>Daiquiri</h3>
    <p class="cubic">The most-ordered rum drink in the world, this fruity favourite is made with lime juice, white rum, and sugar syrup, shaken, then served.</p>
    <img class="img_fav" src="http://static6.businessinsider.de/image/57f4e8a6dd08954e358b48d2-1200/3-daiquiri-the-most-ordered-rum-drink-in-the-world-this-fruity-favourite-is-made-with-lime-juice-white-rum-and-sugar-syrup-shaken-then-served.jpg">
    <br>
    <br>
    <br>
    <br>
    <h3>Negroni</h3>
    <p class="cubic">This Italian favourite is going nowhere, and is the second-most-orderered cocktail in the world. It's made with a third, third, and a third of Campari, sweet vermouth, and gin.</p>
    <img class="img_fav" src="http://static1.businessinsider.de/image/57f4e8a7dd08954e358b48d4-1200/2-negroni-this-italian-favourite-is-going-nowhere-and-is-the-second-most-orderered-cocktail-in-the-world-its-made-with-a-third-third-and-a-third-of-campari-sweet-vermouth-and-gin.jpg">
    <br>
    <br>
    <br>
    <br>
    <h3>Old Fashioned</h3>
    <p class="cubic">This trusty, refined drink has held its spot at the top, which indicates its revival is far from over. It's usually made with a sugar cube and Angostura bitters, crushed, and stirred with a large ice cube and bourbon.</p>
    <img class="img_fav" src="http://static2.businessinsider.de/image/57f4e8a8dd08954e358b48d5-1200/1-old-fashioned-this-trusty-refined-drink-has-held-its-spot-at-the-top-which-indicates-its-revival-is-far-from-over-its-usually-made-with-a-sugar-cube-and-angostura-bitters-crushed-and-stirred-with-a-large-ice-cube-and-bourbon.jpg">
    <br>
    <br>
    <br>
    <a href="#cook" class="align-center">Back Up</a>
  </div>
</div>

app/views/pages/home.html.erb
<div class="back_home">
  <div class="typed_wrap">
     <span id="banner-typed-text"></span>
  </div>
  <br>
  <br>
  <br>


  <div class="container">
    <div class="cards fluid">
      <%= link_to cocktails_path do %>
      <div class="card">
        <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.2)), url('https://getbento.imgix.net/accounts/83ae39a3b3de63e64d52563cd1e9f71d/media/images/61350Union_Square_Cafe_cocktails.jpg?w=600&fit=max&auto=compress,format&h=600');">
          <span class="card-category">Cocktails</span>
          <div class="card-description">
            <p>Look at the favorite cocktails...</p>
          </div>
        </div>
        <div class="card-footer">
          <p>Last Update 14.02.18</p>
          <div class="controls">
            <a href="#"><i class="fa fa-star"></i></a>
            <a href="#"><i class="fa fa-heart"></i></a>
            <a href="#"><i class="fa fa-share"></i></a>
          </div>
        </div>
      </div>
      <% end %>
      <div class="card">
        <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.2)), url('https://i.pinimg.com/564x/1b/0c/31/1b0c31e2d6b0a99928663a033ff26da4--international-trade-trade-show.jpg');">
          <span class="card-category">Locations</span>
          <div class="card-description">
            <p>Look at the many areas we have covered...</p>
          </div>
          <a class="card-link" href="#"></a>
        </div>
        <div class="card-footer">
          <p>Last Update 14.02.18</p>
          <div class="controls">
            <a href="#"><i class="fa fa-star"></i></a>
            <a href="#"><i class="fa fa-heart"></i></a>
            <a href="#"><i class="fa fa-share"></i></a>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.2)), url('https://www.kingscross.co.uk/media/415_Caravan_KX_Bar_015-800x800.jpg');">
          <span class="card-category">Our Community</span>
          <div class="card-description">
            <p>Look at our great community...</p>
          </div>
          <a class="card-link" href="#"></a>
        </div>
        <div class="card-footer">
          <p>Last Update 14.02.18</p>
          <div class="controls">
            <a href="#"><i class="fa fa-star"></i></a>
            <a href="#"><i class="fa fa-heart"></i></a>
            <a href="#"><i class="fa fa-share"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "https://d30y9cdsu7xlg0.cloudfront.net/png/100531-200.png" %>
  <% end %>

    <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <div class="nav_links">
    <!-- Links -->
      <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Cocktails", cocktails_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Locations", locations_path, class: "navbar-wagon-item navbar-wagon-link" %>
    </div>
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "https://d30y9cdsu7xlg0.cloudfront.net/png/100531-200.png" %>
  <% end %>
  </div>
</div>